# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88728cc6431d7f49529511c08f7aefcb94658f79a05c51a0443b904de66e575fd29811f0bf8950299cda9464caa97b4826ee14df9dda7ba3f9ad427a0fd01fd0

test:
  secret_key_base: 3b99c347c391760b878f8235f565519063f2c66cc01e36cbec3cf6a324e637220c57dbd4842f550c409bce877e8d0550623bac0fa97afcb457094500033e2754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
